# Generated by Django 5.0.3 on 2024-06-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0072_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
