# Generated by Django 5.0.3 on 2024-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0073_user_super_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer')], default='Developer', max_length=20),
        ),
    ]
